package dev.aparikh.aipoweredsearch.indexing;

import dev.aparikh.aipoweredsearch.indexing.model.BatchIndexRequest;
import dev.aparikh.aipoweredsearch.indexing.model.IndexRequest;
import dev.aparikh.aipoweredsearch.indexing.model.IndexResponse;
import dev.aparikh.aipoweredsearch.solr.vectorstore.VectorStoreFactory;
import org.springframework.ai.vectorstore.VectorStore;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.verify;

/**
 * Unit tests for IndexService with VectorStoreFactory injection.
 */
@ExtendWith(MockitoExtension.class)
class IndexServiceTest {

    @Mock
    private VectorStoreFactory vectorStoreFactory;

    @Mock
    private VectorStore vectorStore;

    private IndexService indexService;

    @BeforeEach
    void setUp() {
        indexService = new IndexService(vectorStoreFactory);
        org.mockito.Mockito.when(vectorStoreFactory.forCollection(org.mockito.ArgumentMatchers.anyString()))
                .thenReturn(vectorStore);
    }

    @Test
    void shouldIndexSingleDocumentSuccessfully() {
        // Given
        String collection = "test-collection";
        IndexRequest request = new IndexRequest(
                "doc-1",
                "Test document content",
                Map.of("category", "test", "author", "John Doe")
        );

        doNothing().when(vectorStore).add(anyList());

        // When
        IndexResponse response = indexService.indexDocument(collection, request);

        // Then
        assertNotNull(response);
        assertEquals(1, response.indexed());
        assertEquals(0, response.failed());
        assertThat(response.documentIds()).contains("doc-1");
        assertThat(response.message()).contains("Successfully indexed document");

        verify(vectorStore).add(anyList());
    }

    @Test
    void shouldIndexDocumentWithAutoGeneratedId() {
        // Given
        String collection = "test-collection";
        IndexRequest request = new IndexRequest(
                null,
                "Test document without ID",
                Map.of("type", "auto-id")
        );

        doNothing().when(vectorStore).add(anyList());

        // When
        IndexResponse response = indexService.indexDocument(collection, request);

        // Then
        assertNotNull(response);
        assertEquals(1, response.indexed());
        assertEquals(0, response.failed());
        assertThat(response.documentIds()).hasSize(1);

        String generatedId = response.documentIds().get(0);
        assertNotNull(generatedId);
        assertThat(generatedId).isNotEmpty();
    }

    @Test
    void shouldBatchIndexMultipleDocuments() {
        // Given
        String collection = "test-collection";
        List<IndexRequest> documents = List.of(
                new IndexRequest("doc-1", "First document", Map.of("order", 1)),
                new IndexRequest("doc-2", "Second document", Map.of("order", 2)),
                new IndexRequest("doc-3", "Third document", Map.of("order", 3))
        );
        BatchIndexRequest batchRequest = new BatchIndexRequest(documents);

        doNothing().when(vectorStore).add(anyList());

        // When
        IndexResponse response = indexService.indexDocuments(collection, batchRequest);

        // Then
        assertNotNull(response);
        assertEquals(3, response.indexed());
        assertEquals(0, response.failed());
        assertThat(response.documentIds()).containsExactlyInAnyOrder("doc-1", "doc-2", "doc-3");
        assertThat(response.message()).contains("Successfully indexed 3 documents");
        verify(vectorStore).add(anyList());
    }

    @Test
    void shouldHandleIndexingFailure() {
        // Given
        String collection = "test-collection";
        IndexRequest request = new IndexRequest(
                "doc-fail",
                "This will fail",
                null
        );

        doThrow(new RuntimeException("Solr connection failed"))
                .when(vectorStore).add(anyList());

        // When
        IndexResponse response = indexService.indexDocument(collection, request);

        // Then
        assertNotNull(response);
        assertEquals(0, response.indexed());
        assertEquals(1, response.failed());
        assertThat(response.documentIds()).isEmpty();
        assertThat(response.message()).contains("Failed to index document");
        assertThat(response.message()).contains("Solr connection failed");
    }

    @Test
    void shouldHandleBatchIndexingFailure() {
        // Given
        String collection = "test-collection";
        List<IndexRequest> documents = List.of(
                new IndexRequest("doc-1", "First document", null),
                new IndexRequest("doc-2", "Second document", null)
        );
        BatchIndexRequest batchRequest = new BatchIndexRequest(documents);

        doThrow(new RuntimeException("Batch indexing failed"))
                .when(vectorStore).add(anyList());

        // When
        IndexResponse response = indexService.indexDocuments(collection, batchRequest);

        // Then
        assertNotNull(response);
        assertEquals(2, response.indexed());
        assertEquals(0, response.failed());
        assertThat(response.documentIds()).containsExactlyInAnyOrder("doc-1", "doc-2");
        assertThat(response.message()).contains("Batch indexing partially failed");
    }
}
